os: linux
dist: xenial
language: node_js
node_js:
  - 14
cache:
  yarn: true
  directories:
    - .jest
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - stage: 'lint'
      name: 'Lint commit and code'
      if: branch != master
      script:
        - commitlint-travis
        - yarn lint
        - yarn types
    - stage: 'unit tests'
      name: 'Run unit tests'
      script:
        - yarn jest --ci
    - stage: deploy
      name: 'Deploy to Staging'
      if: branch = master
      script:
        - yarn deploy:staging
